{{- range .Values.adapters }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ $.Values.gcp.project | quote }}
spec:
  displayName: {{ .serviceAccount.displayName | quote }}
  description: {{ .serviceAccount.description | quote }}
{{- end }}
