hyperfleet-adapter:
  image:
    registry: quay.io/openshift-hyperfleet
    repository: hyperfleet-adapter
    pullPolicy: Always
    tag: v0.1.0

  adapterConfig:
    create: true

  adapterTaskConfig:
    create: false
    configMapName: adapter-signing-key-resources

  broker:
    create: true
    googlepubsub:
      projectId: ""
      subscriptionId: hyperfleet-cluster-events-adapter-signing-key
      topic: hyperfleet-cluster-events
      createTopicIfMissing: false
      createSubscriptionIfMissing: false

  serviceAccount:
    create: true
    name: hyperfleet-adapter-signing-key
    annotations:
      iam.gke.io/gcp-service-account: hyperfleet-adapter-hc@dev-reg-us-c1-ckandagcd56.iam.gserviceaccount.com

  env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: KEYGEN_IMAGE
      value: "google/cloud-sdk:slim"
    - name: KEYGEN_GCP_SA
      value: ""

  rbac:
    resources:
      - namespaces
      - secrets
      - configmaps
